[default]
[default.local_start_api]
[default.local_start_api.parameters]
port = 5000
host = "0.0.0.0"
docker_network = "retirement-portfolio_default"

[default.build]
[default.build.parameters]
use_container = true

[default.deploy]
[default.deploy.parameters]
stack_name = "retirement-portfolio"
s3_bucket = ""
s3_prefix = "retirement-portfolio"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = ""